stages:
  - prechecks
  - test

changelog_check:
  image: python:3.10.4-buster
  stage: prechecks
  script:
    - git fetch
    - FILES_CHANGED=$(git diff --name-only $CI_MERGE_REQUEST_DIFF_BASE_SHA...HEAD)
    - |+
      for i in $FILES_CHANGED
      do
        if [[ "$i" == "CHANGELOG.md" ]]
        then
          exit 0
        fi
      done
      exit 1
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

test_linting:
  image: condaforge/miniforge3:24.9.2-0
  stage: prechecks
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - apt update && apt --quiet --assume-yes install -y libmagic1
  script:
    - mamba env create -n tronmake -f environment.yaml
    - source /opt/conda/bin/activate tronmake
    - snakemake --lint


test_pipeline:
  image: condaforge/miniforge3:24.11.3-2
  stage: test
  before_script:
    - DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt update && DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt --quiet --assume-yes install -y libxml2
  script:
    - mamba env create -f tests/ci.yaml
    - source /opt/conda/bin/activate Snakemake
    - pip install pytest-workflow==2.0.1 pytest==8.0.2
    - make test
