name: kmer
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - bioconda::snakemake=9.1.6
  - conda-forge::pytest-workflow
  - conda-forge::mamba
  - conda-forge::python=3.12.4
  - pip
  - make
  - pandas
  - loguru
  - snakemake-storage-plugin-http
  - snakemake-executor-plugin-cluster-generic
  - snakemake-executor-plugin-slurm
