name: kmer
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - bioconda::snakemake=8.16
  - conda-forge::pytest-workflow
  - conda-forge::mamba
  - pip
  - pip:
    - snakemake-storage-plugin-http
    - snakemake-executor-plugin-cluster-generic
    - snakemake-executor-plugin-slurm
