[workspace]
authors = ["Johannes Hausmann"]
channels = ["conda-forge", "bioconda"]
name = "tronmake-kmer-pipeline"
platforms = ["linux-64"]
version = "3.1.0"

[dependencies]
snakemake = { version = ">=9.20", channel = "bioconda" }
pandas = "*"
loguru = "*"
conda = { version = ">=26.5", channel = "conda-forge"}
snakemake-storage-plugin-http = "*"

[feature.slurm.pypi-dependencies]
snakemake-executor-plugin-slurm = "*"
snakemake-executor-plugin-cluster-generic = "*"

[feature.style-md.dependencies]
mdformat = ">=0.7.22,<0.8"
mdformat-gfm = ">=1.0.0,<2"
mdformat-shfmt = ">=0.2.0,<0.3"
mdformat-tables = ">=1.0.0,<2"

[feature.style-md.tasks]
style-md = { cmd = "mdformat **/*.md", default-environment = "style-md", description = "Auto-format markdown files" }
lint-md = { cmd = "mdformat --check **/*.md", default-environment = "style-md", description = "Lint markdown files" }

[feature.style-python.dependencies]
black = ">=26.3.1,<27"

[feature.style-python.tasks]
style-python = { cmd = "black **/*.py --force-exclude 'workflow/scripts/simple_bf_size_estimate_python2.py'", default-environment = "style-python", description = "Auto-format python files" }
lint-python = { cmd = "black --check --force-exclude 'workflow/scripts/simple_bf_size_estimate_python2.py' **/*.py", default-environment = "style-python", description = "Lint python files" }

[feature.style-snakemake.dependencies]
snakefmt = ">=1.1.0,<2"

[feature.style-snakemake.tasks]
style-snakemake = { cmd = "snakefmt workflow/", default-environment = "style-snakemake", description = "Auto-format Snakemake files" }
lint-snakemake = { cmd = "snakefmt --check workflow/", default-environment = "style-snakemake", description = "Lint Snakemake files" }

[feature.style-yaml.dependencies]
yamlfmt = ">=0.21.0,<0.22"

[feature.style-yaml.tasks]
style-yaml = { cmd = "yamlfmt **/*.yaml **/*.yml .github/**/*.yaml .github/**/*.yml", default-environment = "style-yaml", description = "Auto-format yaml files" }
lint-yaml = { cmd = "yamlfmt -lint **/*.yaml **/*.yml .github/**/*.yaml .github/**/*.yml", default-environment = "style-yaml", description = "Lint yaml files" }

[feature.rule-env-pinning.dependencies]
snakedeploy = ">=0.16.0,<0.17"

[feature.rule-env-pinning.tasks]
pin-rule-envs = { cmd = "snakedeploy pin-conda-envs workflow/envs/*.yaml", default-environment = "rule-env-pinning", description = "Pin conda environments in `workflow/envs/*.yaml` with snakedeploy." }

[feature.test.dependencies]
pytest = "*"
pytest-workflow = "*"

[feature.test.tasks]
test-ci = { cmd = "pytest --git-aware --symlink --stderr-bytes 100000", default-environment = "test", description = "Run the test suite." }

[feature.test.tasks.test-syntax]
cmd = "pytest --tag dryrun --git-aware --symlink --stderr-bytes 100000"
default-environment = "test"
description = "Run sytax check" 


[environments]
default = { features = ["slurm"] }
test = { features = ["test"] }
test-syntax = { features = ["test"] }
style-md = { features = ["style-md"], no-default-feature = true }
style-python = { features = ["style-python"], no-default-feature = true }
style-snakemake = { features = ["style-snakemake"], no-default-feature = true }
style-yaml = { features = ["style-yaml"], no-default-feature = true }
rule-env-pinning = { features = ["rule-env-pinning"], no-default-feature = true }

[tasks.lint-workflow]
cmd = """\
    snakemake \
        -s workflow/Snakefile \
        --software-deployment-method conda \
        --lint\
    """
description = "Snakemake `--lint` of `workflow/Snakefile`."

# Order matters, these are laid out from most likely to fail during development
# to least likely.
[tasks.style]
depends-on = [
  "style-snakemake",
  "style-python",
  "style-md",
  "style-yaml"
]
description = "Auto-format all files (Snakemake, Python, R, Markdown, YAML)."

[tasks.lint]
depends-on = [
  "lint-workflow",
  "lint-snakemake",
  "lint-python",
  "lint-md",
  "lint-yaml"
]
description = "Run all linters (Snakemake, Python, R, Markdown, shell, YAML, TOML)."