$schema: http://json-schema.org/draft-07/schema#
title: Generated schema for Root
type: object
properties:
  modus:
    type: object
    properties:
      query:
        type: boolean
      indexing:
        type: boolean
    required:
      - query
      - indexing
  indexing:
    type: object
    properties:
      samples:
        type: string
      kmer_size:
        type: number
      cutoff:
        type: number
      method:
        type: string
      fpr:
        type: number
      quantitative_index:
        type: boolean
    required:
      - samples
      - kmer_size
      - cutoff
      - method
      - fpr
      - quantitative_index
  query:
    type: object
    properties:
      index:
        type: string
      query_fasta:
        type: string
      kmer_ratio:
        type: number
      method:
        type: string
      findere_z:
        type: number
    required:
      - index
      - query_fasta
      - kmer_ratio
      - method
      - findere_z
required:
  - modus
  - indexing
  - query
